// This file was generated by counterfeiter
package efsfakes

import (
	"sync"

	"code.cloudfoundry.org/efsbroker/efsbroker"
	"github.com/aws/aws-sdk-go/service/efs"
)

type FakeEFSService struct {
	CreateFileSystemStub        func(*efs.CreateFileSystemInput) (*efs.FileSystemDescription, error)
	createFileSystemMutex       sync.RWMutex
	createFileSystemArgsForCall []struct {
		arg1 *efs.CreateFileSystemInput
	}
	createFileSystemReturns struct {
		result1 *efs.FileSystemDescription
		result2 error
	}
	DeleteFileSystemStub        func(*efs.DeleteFileSystemInput) (*efs.DeleteFileSystemOutput, error)
	deleteFileSystemMutex       sync.RWMutex
	deleteFileSystemArgsForCall []struct {
		arg1 *efs.DeleteFileSystemInput
	}
	deleteFileSystemReturns struct {
		result1 *efs.DeleteFileSystemOutput
		result2 error
	}
	DescribeFileSystemsStub        func(*efs.DescribeFileSystemsInput) (*efs.DescribeFileSystemsOutput, error)
	describeFileSystemsMutex       sync.RWMutex
	describeFileSystemsArgsForCall []struct {
		arg1 *efs.DescribeFileSystemsInput
	}
	describeFileSystemsReturns struct {
		result1 *efs.DescribeFileSystemsOutput
		result2 error
	}
	CreateMountTargetStub        func(*efs.CreateMountTargetInput) (*efs.MountTargetDescription, error)
	createMountTargetMutex       sync.RWMutex
	createMountTargetArgsForCall []struct {
		arg1 *efs.CreateMountTargetInput
	}
	createMountTargetReturns struct {
		result1 *efs.MountTargetDescription
		result2 error
	}
	DeleteMountTargetStub        func(*efs.DeleteMountTargetInput) (*efs.DeleteMountTargetOutput, error)
	deleteMountTargetMutex       sync.RWMutex
	deleteMountTargetArgsForCall []struct {
		arg1 *efs.DeleteMountTargetInput
	}
	deleteMountTargetReturns struct {
		result1 *efs.DeleteMountTargetOutput
		result2 error
	}
	DescribeMountTargetsStub        func(*efs.DescribeMountTargetsInput) (*efs.DescribeMountTargetsOutput, error)
	describeMountTargetsMutex       sync.RWMutex
	describeMountTargetsArgsForCall []struct {
		arg1 *efs.DescribeMountTargetsInput
	}
	describeMountTargetsReturns struct {
		result1 *efs.DescribeMountTargetsOutput
		result2 error
	}
}

func (fake *FakeEFSService) CreateFileSystem(arg1 *efs.CreateFileSystemInput) (*efs.FileSystemDescription, error) {
	fake.createFileSystemMutex.Lock()
	fake.createFileSystemArgsForCall = append(fake.createFileSystemArgsForCall, struct {
		arg1 *efs.CreateFileSystemInput
	}{arg1})
	fake.createFileSystemMutex.Unlock()
	if fake.CreateFileSystemStub != nil {
		return fake.CreateFileSystemStub(arg1)
	} else {
		return fake.createFileSystemReturns.result1, fake.createFileSystemReturns.result2
	}
}

func (fake *FakeEFSService) CreateFileSystemCallCount() int {
	fake.createFileSystemMutex.RLock()
	defer fake.createFileSystemMutex.RUnlock()
	return len(fake.createFileSystemArgsForCall)
}

func (fake *FakeEFSService) CreateFileSystemArgsForCall(i int) *efs.CreateFileSystemInput {
	fake.createFileSystemMutex.RLock()
	defer fake.createFileSystemMutex.RUnlock()
	return fake.createFileSystemArgsForCall[i].arg1
}

func (fake *FakeEFSService) CreateFileSystemReturns(result1 *efs.FileSystemDescription, result2 error) {
	fake.CreateFileSystemStub = nil
	fake.createFileSystemReturns = struct {
		result1 *efs.FileSystemDescription
		result2 error
	}{result1, result2}
}

func (fake *FakeEFSService) DeleteFileSystem(arg1 *efs.DeleteFileSystemInput) (*efs.DeleteFileSystemOutput, error) {
	fake.deleteFileSystemMutex.Lock()
	fake.deleteFileSystemArgsForCall = append(fake.deleteFileSystemArgsForCall, struct {
		arg1 *efs.DeleteFileSystemInput
	}{arg1})
	fake.deleteFileSystemMutex.Unlock()
	if fake.DeleteFileSystemStub != nil {
		return fake.DeleteFileSystemStub(arg1)
	} else {
		return fake.deleteFileSystemReturns.result1, fake.deleteFileSystemReturns.result2
	}
}

func (fake *FakeEFSService) DeleteFileSystemCallCount() int {
	fake.deleteFileSystemMutex.RLock()
	defer fake.deleteFileSystemMutex.RUnlock()
	return len(fake.deleteFileSystemArgsForCall)
}

func (fake *FakeEFSService) DeleteFileSystemArgsForCall(i int) *efs.DeleteFileSystemInput {
	fake.deleteFileSystemMutex.RLock()
	defer fake.deleteFileSystemMutex.RUnlock()
	return fake.deleteFileSystemArgsForCall[i].arg1
}

func (fake *FakeEFSService) DeleteFileSystemReturns(result1 *efs.DeleteFileSystemOutput, result2 error) {
	fake.DeleteFileSystemStub = nil
	fake.deleteFileSystemReturns = struct {
		result1 *efs.DeleteFileSystemOutput
		result2 error
	}{result1, result2}
}

func (fake *FakeEFSService) DescribeFileSystems(arg1 *efs.DescribeFileSystemsInput) (*efs.DescribeFileSystemsOutput, error) {
	fake.describeFileSystemsMutex.Lock()
	fake.describeFileSystemsArgsForCall = append(fake.describeFileSystemsArgsForCall, struct {
		arg1 *efs.DescribeFileSystemsInput
	}{arg1})
	fake.describeFileSystemsMutex.Unlock()
	if fake.DescribeFileSystemsStub != nil {
		return fake.DescribeFileSystemsStub(arg1)
	} else {
		return fake.describeFileSystemsReturns.result1, fake.describeFileSystemsReturns.result2
	}
}

func (fake *FakeEFSService) DescribeFileSystemsCallCount() int {
	fake.describeFileSystemsMutex.RLock()
	defer fake.describeFileSystemsMutex.RUnlock()
	return len(fake.describeFileSystemsArgsForCall)
}

func (fake *FakeEFSService) DescribeFileSystemsArgsForCall(i int) *efs.DescribeFileSystemsInput {
	fake.describeFileSystemsMutex.RLock()
	defer fake.describeFileSystemsMutex.RUnlock()
	return fake.describeFileSystemsArgsForCall[i].arg1
}

func (fake *FakeEFSService) DescribeFileSystemsReturns(result1 *efs.DescribeFileSystemsOutput, result2 error) {
	fake.DescribeFileSystemsStub = nil
	fake.describeFileSystemsReturns = struct {
		result1 *efs.DescribeFileSystemsOutput
		result2 error
	}{result1, result2}
}

func (fake *FakeEFSService) CreateMountTarget(arg1 *efs.CreateMountTargetInput) (*efs.MountTargetDescription, error) {
	fake.createMountTargetMutex.Lock()
	fake.createMountTargetArgsForCall = append(fake.createMountTargetArgsForCall, struct {
		arg1 *efs.CreateMountTargetInput
	}{arg1})
	fake.createMountTargetMutex.Unlock()
	if fake.CreateMountTargetStub != nil {
		return fake.CreateMountTargetStub(arg1)
	} else {
		return fake.createMountTargetReturns.result1, fake.createMountTargetReturns.result2
	}
}

func (fake *FakeEFSService) CreateMountTargetCallCount() int {
	fake.createMountTargetMutex.RLock()
	defer fake.createMountTargetMutex.RUnlock()
	return len(fake.createMountTargetArgsForCall)
}

func (fake *FakeEFSService) CreateMountTargetArgsForCall(i int) *efs.CreateMountTargetInput {
	fake.createMountTargetMutex.RLock()
	defer fake.createMountTargetMutex.RUnlock()
	return fake.createMountTargetArgsForCall[i].arg1
}

func (fake *FakeEFSService) CreateMountTargetReturns(result1 *efs.MountTargetDescription, result2 error) {
	fake.CreateMountTargetStub = nil
	fake.createMountTargetReturns = struct {
		result1 *efs.MountTargetDescription
		result2 error
	}{result1, result2}
}

func (fake *FakeEFSService) DeleteMountTarget(arg1 *efs.DeleteMountTargetInput) (*efs.DeleteMountTargetOutput, error) {
	fake.deleteMountTargetMutex.Lock()
	fake.deleteMountTargetArgsForCall = append(fake.deleteMountTargetArgsForCall, struct {
		arg1 *efs.DeleteMountTargetInput
	}{arg1})
	fake.deleteMountTargetMutex.Unlock()
	if fake.DeleteMountTargetStub != nil {
		return fake.DeleteMountTargetStub(arg1)
	} else {
		return fake.deleteMountTargetReturns.result1, fake.deleteMountTargetReturns.result2
	}
}

func (fake *FakeEFSService) DeleteMountTargetCallCount() int {
	fake.deleteMountTargetMutex.RLock()
	defer fake.deleteMountTargetMutex.RUnlock()
	return len(fake.deleteMountTargetArgsForCall)
}

func (fake *FakeEFSService) DeleteMountTargetArgsForCall(i int) *efs.DeleteMountTargetInput {
	fake.deleteMountTargetMutex.RLock()
	defer fake.deleteMountTargetMutex.RUnlock()
	return fake.deleteMountTargetArgsForCall[i].arg1
}

func (fake *FakeEFSService) DeleteMountTargetReturns(result1 *efs.DeleteMountTargetOutput, result2 error) {
	fake.DeleteMountTargetStub = nil
	fake.deleteMountTargetReturns = struct {
		result1 *efs.DeleteMountTargetOutput
		result2 error
	}{result1, result2}
}

func (fake *FakeEFSService) DescribeMountTargets(arg1 *efs.DescribeMountTargetsInput) (*efs.DescribeMountTargetsOutput, error) {
	fake.describeMountTargetsMutex.Lock()
	fake.describeMountTargetsArgsForCall = append(fake.describeMountTargetsArgsForCall, struct {
		arg1 *efs.DescribeMountTargetsInput
	}{arg1})
	fake.describeMountTargetsMutex.Unlock()
	if fake.DescribeMountTargetsStub != nil {
		return fake.DescribeMountTargetsStub(arg1)
	} else {
		return fake.describeMountTargetsReturns.result1, fake.describeMountTargetsReturns.result2
	}
}

func (fake *FakeEFSService) DescribeMountTargetsCallCount() int {
	fake.describeMountTargetsMutex.RLock()
	defer fake.describeMountTargetsMutex.RUnlock()
	return len(fake.describeMountTargetsArgsForCall)
}

func (fake *FakeEFSService) DescribeMountTargetsArgsForCall(i int) *efs.DescribeMountTargetsInput {
	fake.describeMountTargetsMutex.RLock()
	defer fake.describeMountTargetsMutex.RUnlock()
	return fake.describeMountTargetsArgsForCall[i].arg1
}

func (fake *FakeEFSService) DescribeMountTargetsReturns(result1 *efs.DescribeMountTargetsOutput, result2 error) {
	fake.DescribeMountTargetsStub = nil
	fake.describeMountTargetsReturns = struct {
		result1 *efs.DescribeMountTargetsOutput
		result2 error
	}{result1, result2}
}

var _ efsbroker.EFSService = new(FakeEFSService)
