// This file was generated by counterfeiter
package efsfakes

import (
	"sync"

	"code.cloudfoundry.org/efsbroker/efsbroker"
)

type FakeOperation struct {
	ExecuteStub        func()
	executeMutex       sync.RWMutex
	executeArgsForCall []struct{}
}

func (fake *FakeOperation) Execute() {
	fake.executeMutex.Lock()
	fake.executeArgsForCall = append(fake.executeArgsForCall, struct{}{})
	fake.executeMutex.Unlock()
	if fake.ExecuteStub != nil {
		fake.ExecuteStub()
	}
}

func (fake *FakeOperation) ExecuteCallCount() int {
	fake.executeMutex.RLock()
	defer fake.executeMutex.RUnlock()
	return len(fake.executeArgsForCall)
}

var _ efsbroker.Operation = new(FakeOperation)
