// This file was generated by counterfeiter
package efsdriverfakes

import (
	"sync"

	"code.cloudfoundry.org/efsbroker/efsdriver"
	"github.com/aws/aws-sdk-go/service/efs"
)

type FakeEFSService struct {
	CreateFileSystemStub        func(*efs.CreateFileSystemInput) (*efs.FileSystemDescription, error)
	createFileSystemMutex       sync.RWMutex
	createFileSystemArgsForCall []struct {
		arg1 *efs.CreateFileSystemInput
	}
	createFileSystemReturns struct {
		result1 *efs.FileSystemDescription
		result2 error
	}
	DeleteFileSystemStub        func(*efs.DeleteFileSystemInput) (*efs.DeleteFileSystemOutput, error)
	deleteFileSystemMutex       sync.RWMutex
	deleteFileSystemArgsForCall []struct {
		arg1 *efs.DeleteFileSystemInput
	}
	deleteFileSystemReturns struct {
		result1 *efs.DeleteFileSystemOutput
		result2 error
	}
	DescribeFileSystemsStub        func(*efs.DescribeFileSystemsInput) (*efs.DescribeFileSystemsOutput, error)
	describeFileSystemsMutex       sync.RWMutex
	describeFileSystemsArgsForCall []struct {
		arg1 *efs.DescribeFileSystemsInput
	}
	describeFileSystemsReturns struct {
		result1 *efs.DescribeFileSystemsOutput
		result2 error
	}
}

func (fake *FakeEFSService) CreateFileSystem(arg1 *efs.CreateFileSystemInput) (*efs.FileSystemDescription, error) {
	fake.createFileSystemMutex.Lock()
	fake.createFileSystemArgsForCall = append(fake.createFileSystemArgsForCall, struct {
		arg1 *efs.CreateFileSystemInput
	}{arg1})
	fake.createFileSystemMutex.Unlock()
	if fake.CreateFileSystemStub != nil {
		return fake.CreateFileSystemStub(arg1)
	} else {
		return fake.createFileSystemReturns.result1, fake.createFileSystemReturns.result2
	}
}

func (fake *FakeEFSService) CreateFileSystemCallCount() int {
	fake.createFileSystemMutex.RLock()
	defer fake.createFileSystemMutex.RUnlock()
	return len(fake.createFileSystemArgsForCall)
}

func (fake *FakeEFSService) CreateFileSystemArgsForCall(i int) *efs.CreateFileSystemInput {
	fake.createFileSystemMutex.RLock()
	defer fake.createFileSystemMutex.RUnlock()
	return fake.createFileSystemArgsForCall[i].arg1
}

func (fake *FakeEFSService) CreateFileSystemReturns(result1 *efs.FileSystemDescription, result2 error) {
	fake.CreateFileSystemStub = nil
	fake.createFileSystemReturns = struct {
		result1 *efs.FileSystemDescription
		result2 error
	}{result1, result2}
}

func (fake *FakeEFSService) DeleteFileSystem(arg1 *efs.DeleteFileSystemInput) (*efs.DeleteFileSystemOutput, error) {
	fake.deleteFileSystemMutex.Lock()
	fake.deleteFileSystemArgsForCall = append(fake.deleteFileSystemArgsForCall, struct {
		arg1 *efs.DeleteFileSystemInput
	}{arg1})
	fake.deleteFileSystemMutex.Unlock()
	if fake.DeleteFileSystemStub != nil {
		return fake.DeleteFileSystemStub(arg1)
	} else {
		return fake.deleteFileSystemReturns.result1, fake.deleteFileSystemReturns.result2
	}
}

func (fake *FakeEFSService) DeleteFileSystemCallCount() int {
	fake.deleteFileSystemMutex.RLock()
	defer fake.deleteFileSystemMutex.RUnlock()
	return len(fake.deleteFileSystemArgsForCall)
}

func (fake *FakeEFSService) DeleteFileSystemArgsForCall(i int) *efs.DeleteFileSystemInput {
	fake.deleteFileSystemMutex.RLock()
	defer fake.deleteFileSystemMutex.RUnlock()
	return fake.deleteFileSystemArgsForCall[i].arg1
}

func (fake *FakeEFSService) DeleteFileSystemReturns(result1 *efs.DeleteFileSystemOutput, result2 error) {
	fake.DeleteFileSystemStub = nil
	fake.deleteFileSystemReturns = struct {
		result1 *efs.DeleteFileSystemOutput
		result2 error
	}{result1, result2}
}

func (fake *FakeEFSService) DescribeFileSystems(arg1 *efs.DescribeFileSystemsInput) (*efs.DescribeFileSystemsOutput, error) {
	fake.describeFileSystemsMutex.Lock()
	fake.describeFileSystemsArgsForCall = append(fake.describeFileSystemsArgsForCall, struct {
		arg1 *efs.DescribeFileSystemsInput
	}{arg1})
	fake.describeFileSystemsMutex.Unlock()
	if fake.DescribeFileSystemsStub != nil {
		return fake.DescribeFileSystemsStub(arg1)
	} else {
		return fake.describeFileSystemsReturns.result1, fake.describeFileSystemsReturns.result2
	}
}

func (fake *FakeEFSService) DescribeFileSystemsCallCount() int {
	fake.describeFileSystemsMutex.RLock()
	defer fake.describeFileSystemsMutex.RUnlock()
	return len(fake.describeFileSystemsArgsForCall)
}

func (fake *FakeEFSService) DescribeFileSystemsArgsForCall(i int) *efs.DescribeFileSystemsInput {
	fake.describeFileSystemsMutex.RLock()
	defer fake.describeFileSystemsMutex.RUnlock()
	return fake.describeFileSystemsArgsForCall[i].arg1
}

func (fake *FakeEFSService) DescribeFileSystemsReturns(result1 *efs.DescribeFileSystemsOutput, result2 error) {
	fake.DescribeFileSystemsStub = nil
	fake.describeFileSystemsReturns = struct {
		result1 *efs.DescribeFileSystemsOutput
		result2 error
	}{result1, result2}
}

var _ efsdriver.EFSService = new(FakeEFSService)
